---
# Configuration directives for Travis CI
# --------------------------------------

# [Travis CI] http://travis-ci.org
# [configuration] http://about.travis-ci.org/docs/user/build-configuration/
services: docker

env:
  - distro: ubuntu1604
    playbook: test.yml
  - distro: debian9
    playbook: test.yml
  - distro: debian8
    playbook: test.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export test_idempotence=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/arnobirchler/627e4655465b696a0b521a560bc2206f/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh
  - 
  # Get ip addr
  - >
    docker exec ${container_id} curl --insecure -s --head https://localhost/users/password/new
    | sed -n '1p' | grep -q '200'
    && (echo 'Status code 200 test: pass' && exit 0)
    || (echo 'Status code 200 test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/