---
# tasks file for ansible-role-docker-gitlab 
- name: DOCKER | GITLAB | CREATE composer dir
  command: "mkdir /opt/docker/compose/gitlab -p"
- name: "DOCKER | GITLAB | COPY template"
  template:
    src: "docker-compose.j2"
    dest: "/opt/docker/compose/gitlab/docker-compose.yml"
- name: "DOCKER | GITLAB | RUN"
  command: "cd /opt/docker/compose/gitlab && docker-compose up -d"