---
# tasks file for ansible-role-docker-gitlab 
- name: PWD
  command: "pwd"
- name: DOCKER | GITLAB | CREATE composer dir
  file:
    path: "~/compose/gitlab"
    state: directory
- name: "DOCKER | GITLAB | COPY template"
  template:
    src: "docker-compose.j2"
    dest: "~/compose/gitlab/docker-compose.yml"
- name: "DOCKER | GITLAB | RUN"
  command: "cd ~/compose/gitlab && docker-compose up -d"