---
# tasks file for ansible-role-docker-gitlab 
- name: PWD
  command: "pwd"
- name: DOCKER | GITLAB | CREATE composer dir
  file:
    path: "/home/{{ sudoer }}/docker-compose-gitlab"
    state: directory
    owner: "{{ sudoer }}"
- name: "DOCKER | GITLAB | COPY template"
  template:
    src: "docker-compose.j2"
    dest: "/home/{{ sudoer }}/docker-compose-gitlab/docker-compose.yml"
- name: "DOCKER | GITLAB | RUN"
  command: "docker-compose up -d --project-directory /home/{{ sudoer }}/docker-compose-gitlab -p gitlab --no-recreate --no-color"