---
# tasks file for ansible-role-docker-gitlab 
- name: DOCKER | GITLAB | CREATE composer dir
  file:
    path: "{{ compose_dir }}"
    state: directory
    owner: "{{ sudoer }}"
- name: "DOCKER | GITLAB | COPY template"
  template:
    src: "docker-compose.j2"
    dest: "{{ compose_dir }}/docker-compose.yml"
- name: "DOCKER | GITLAB | RUN"
  command: "cd {{ compose_dir }} && docker-compose up -d --no-recreate --no-color"