---
# tasks file for ansible-role-docker-gitlab 
- name: DOCKER | GITLAB | CREATE composer dir
  file:
    path: "/opt/docker/compose/gitlab"
    state: directory
# - name: DOCKER | GITLAB | CREATE dir
#   file:
#     path: "/opt/docker/compose/gitlab"
#     state: exist
# - name: "DOCKER | GITLAB | COPY template"
#   templates:
#     src: "docker-compose.j2"
#     dst: "/opt/docker/compose/gitlab/docker-compose.yml"
# - name: "DOCKER | GITLAB | RUN"
#   command: "cd /opt/docker/compose/gitlab && docker-compose up -d"